type PriceShippingItem = {
    district: string,
    price: number
};

const priceShipping: PriceShippingItem[] = [
    { district: "Araucaria", price: 2500 },
    { district: "Área Industrial", price: 2500 },
    { district: "Bates", price: 2500 },
    { district: "Beatriz", price: 2000 },
    { district: "Bela Vista", price: 2500 },
    { district: "Bom Jesus", price: 2000 },
    { district: "Boqueirao", price: 2500 },
    { district: "Brusque", price: 1500 },
    { district: "Caca e Tiro", price: 2500 },
    { district: "Caravagio", price: 2000 },
    { district: "Caroba", price: 3000 },
    { district: "CDL", price: 3000 },
    { district: "Centenário", price: 2500 },
    { district: "Centro", price: 1500 },
    { district: "Cidade Alta", price: 3000 },
    { district: "Chapada", price: 2500 },
    { district: "Conta Dinheiro", price: 2500 },
    { district: "Copacabana", price: 2000 },
    { district: "Coral", price: 2000 },
    { district: "Conte", price: 2000 },
    { district: "Cruz de Malta", price: 3000 },
    { district: "Dom Daniel", price: 2500 },
    { district: "Ferrovia", price: 2500 },
    { district: "Frei Rogerio", price: 2000 },
    { district: "Gethal", price: 2000 },
    { district: "Gralha Azul", price: 2500 },
    { district: "Guadalupe", price: 1500 },
    { district: "Guadalajara", price: 2500 },
    { district: "Guarujá", price: 2500 },
    { district: "Golin", price: 2500 },
    { district: "Habitacao", price: 2500 },
    { district: "Ipiranga", price: 2500 },
    { district: "Jardim Celina", price: 2500 },
    { district: "Jardim das Camelias", price: 3000 },
    { district: "Jardim Panorâmico", price: 2500 },
    { district: "Maria Luiza", price: 2500 },
    { district: "Morro do Posto", price: 2500 },
    { district: "Morro Grande", price: 2500 },
    { district: "Nossa Senhora Aparecida", price: 3000 },
    { district: "Passo Fundo", price: 2500 },
    { district: "Penha", price: 2500 },
    { district: "Petrópolis", price: 2500 },
    { district: "Pisani", price: 2500 },
    { district: "Ponte Grande (Jardim Cepar)", price: 2500 },
    { district: "Popular", price: 2500 },
    { district: "Pro-Morar", price: 2000 },
    { district: "Restinga Seca", price: 3000 },
    { district: "Sagrado Coração de Jesus", price: 1500 },
    { district: "Santa Catarina", price: 2000 },
    { district: "Santa Cândida", price: 2500 },
    { district: "Santa Clara", price: 2500 },
    { district: "Santa Helena", price: 2500 },
    { district: "Santa Maria", price: 2000 },
    { district: "Santa Mônica", price: 3000 },
    { district: "Santa Rita", price: 2000 },
    { district: "Santo Antônio", price: 2500 },
    { district: "São Cristóvão", price: 2000 },
    { district: "São Francisco", price: 2000 },
    { district: "Salto Caveiras", price: 3500 },
    { district: "São Luiz", price: 2000 },
    { district: "São Miguel", price: 3000 },
    { district: "São Paulo", price: 3000 },
    { district: "São Pedro", price: 2000 },
    { district: "São Sebastião", price: 2000 },
    { district: "Triângulo", price: 2000 },
    { district: "Tributo", price: 3000 },
    { district: "Universitario", price: 2000 },
    { district: "Varzea", price: 2500 },
    { district: "Vila Comboni", price: 2000 },
    { district: "Vila Maria", price: 2500 },
    { district: "Vila Mariza", price: 2500 },
    { district: "Vila Nova", price: 2000 },
    { district: "Vista Alegre", price: 3000 }
];


export const checkPriceShipping = (city: string, district: string): any => {
    const targetCity = "Lages";
    const isShippingAddress = priceShipping.filter((item:PriceShippingItem) => item.district === district)
    if ((city === targetCity) && isShippingAddress.length > 0) { 
        return isShippingAddress[0].price
    }
}